name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  Build:
    name: LFortran CI (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment_unix.yml

      - uses: hendrikmuhs/ccache-action@main
        with:
          variant: sccache
          key: ${{ github.job }}-${{ matrix.os }}

      - name: Build (Linux / macOS)
        shell: bash -l {0}
        if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
        run: |
            ./build.sh
            export PATH=$CONDA_PREFIX/bin:$PATH

      - name: Print runtime library directory
        shell: bash -l {0}
        if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
        run: |
            lc --get-rtl-header-dir --
            lc --get-rtl-dir --

      - name: Test (Linux / macOS)
        shell: bash -l -e {0}
        if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
        run: |
            export CPATH=$CONDA_PREFIX/include:$CPATH
            lc --show-ast tests/test.cpp
            lc examples/expr2.c --show-asr
            # ./run_tests.py

      - name: Test2 (Linux / macOS)
        shell: bash -l -e {0}
        if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
        run: |
            which clang

            # Test generating object files
            lc examples/expr2.c --backend c -o c_o -c --
            lc examples/expr2.c --backend llvm -o llvm_o -c --
            ls -1

      - name: Test3 (Linux / macOS)
        shell: bash -l -e {0}
        if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
        run: |
            export CPATH=$CONDA_PREFIX/include:$CPATH
            # ./integration_tests/run_tests.py -b gcc llvm wasm c
            # ./integration_tests/run_tests.py -b gcc llvm wasm c -f

      - name: Update Ref Tests and Upload
        shell: bash -l -e {0}
        run: |
            export CPATH=$CONDA_PREFIX/include:$CPATH
            ./run_tests.py -u
            ci/upload_refs.sh
